// Importing TypeScript type for metadata (SEO stuff like title, description)
import type { Metadata } from "next";

// Importing Google Fonts from Next.js built-in font optimization
import { Geist, Geist_Mono } from "next/font/google";

// Global CSS styles - applies to ALL pages
import "./globals.css";

// Our custom Header component - will appear on EVERY page
import Header from "../components/Header";

// Initialize the Geist Sans font with a CSS variable name
// This creates --font-geist-sans that we can use in CSS/Tailwind
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Initialize the Geist Mono font (for code/monospace text)
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Metadata for SEO - this sets the <title> and <meta description> tags
// You should customize this for your business!
export const metadata: Metadata = {
  title: "Bacsal Business Consultancy",
  description: "Generated by create next app",
  icons: {
    icon: "/bacsalicon.png", // Uses the logo from your public folder
    apple: "/bacsalicon.png", // For Apple devices
  },
};

// ROOT LAYOUT - This is the main wrapper for your ENTIRE app
// Think of it like the "shell" that wraps every single page
// Whatever you put here appears on ALL pages (like Header, Footer)
//
// The "children" prop = the actual page content (page.tsx files)
// When you visit "/contact", children = the contact page content
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // The <html> tag - root of the document
    <html lang="en">
      {/* The <body> tag - we add font CSS variables and antialiased text */}
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-white`}
      >
        <div className="bg-white">
        {/* Header appears ABOVE all page content, on EVERY page */}
        <Header />
        </div>
        {/* children = whatever page you're currently viewing */}
        {/* Visit "/" → children = page.tsx (Home) */}
        {/* Visit "/contact" → children = (public)/contact/page.tsx */}
        {/* Visit "/about" → children = (public)/about/page.tsx */}
        {children}

        {/* You could add a <Footer /> here and it would appear on every page too! */}
      </body>
    </html>
  );
}
